### PR TITLE
Adding Hello World.

### PR DESCRIPTION
**Pull request by leonogas**
Now hope it has been fixed.

### CODE REVIEW

**Comment by jabrena** [comment]
In the folder Exercise1:

+ create a `.gitignore` with the following lines:

```
.idea
.gradle
```

That files are autogenerated by the IDE. Repositories are for valuable code, not autogenerated.
Please update the PR with the required files.

Juan Antonio

**Comment by leonogas** [comment]
removing  unnecessary folders.

**Review by jabrena — APPROVED** [review]

**Comment by jabrena** [comment]
What is:

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

What is the main logging dependency used on SpringBoot?
What are the different levels of logging?

**Comment by leonogas** [comment]
What is:
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

**The idea behind it is that’s its a replacement for that other well known logging facade and allow us to logging simpler**

What is the main logging dependency used on SpringBoot?
**Commons Logging**

What are the different levels of logging?
**ERROR, WARN, INFO, DEBUG and TRACE.**
**FATAL is under ERROR level**

**Comment by jabrena** [comment]
For Spring:
https://spring.io/blog/2009/12/04/logging-dependencies-in-spring/

For Spring-Boot, the project use Logback
https://logback.qos.ch/

**Pull request merged**
